{% set name = "ZConfig" %}
{% set version = "4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: a0e4b5277c4cee8060ce335a578ac458f82c240ae96b16659200dbc4d98bfcce

build:
  noarch: python
  entry_points:
    - zconfig = ZConfig.validator:main
    - zconfig_schema2html = ZConfig.schema2html:main

  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  imports:
    - ZConfig
    - ZConfig.components
    - ZConfig.components.basic
    - ZConfig.components.basic.tests
    - ZConfig.components.logger
    - ZConfig.components.logger.tests
    - ZConfig.tests
    - ZConfig.tests.library
    - ZConfig.tests.library.thing
    - ZConfig.tests.library.widget

  commands:
    - zconfig_schema2html -h
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.zope.org/Members/fdrake/zconfig/
  license: ZPL-2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: Structured Configuration Library
  dev_url: https://github.com/zopefoundation/ZConfig

extra:
  recipe-maintainers:
    - jan-janssen
