{%set name = "ZConfig" %}
{%set version = "3.2.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "de0a802e5dfea3c0b3497ccdbe33a5023c4265f950f33e35dd4cf078d2a81b19" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ZConfig
    - ZConfig.components
    - ZConfig.components.basic
    - ZConfig.components.basic.tests
    - ZConfig.components.logger
    - ZConfig.components.logger.tests
    - ZConfig.tests
    - ZConfig.tests.library
    - ZConfig.tests.library.thing
    - ZConfig.tests.library.widget

about:
  home: http://www.zope.org/Members/fdrake/zconfig/
  license: ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Structured Configuration Library'
  dev_url: https://github.com/zopefoundation/ZConfig

extra:
  recipe-maintainers:
    - pmlandwehr
