{% set name = "ZConfig" %}
{% set version = "3.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "a28e95a0ae335795747eccad35b2cb708f37d44c7f325e2acb201e98330b16e5" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - zconfig = ZConfig.validator:main
    - zconfig_schema2html = ZConfig.schema2html:main

  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - ZConfig
    - ZConfig.components
    - ZConfig.components.basic
    - ZConfig.components.basic.tests
    - ZConfig.components.logger
    - ZConfig.components.logger.tests
    - ZConfig.tests
    - ZConfig.tests.library
    - ZConfig.tests.library.thing
    - ZConfig.tests.library.widget

  commands:
    - zconfig_schema2html -h

about:
  home: http://www.zope.org/Members/fdrake/zconfig/
  license: ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: Structured Configuration Library
  dev_url: https://github.com/zopefoundation/ZConfig

extra:
  recipe-maintainers:
    - pmlandwehr
