travis:
  secure:
    BINSTAR_TOKEN: bmElb1GkqpV54cPcJxAqJGwDWFyglnLV1ee7RHJnMNZxkAp+GaKHw/usDQyqDaH8MQsXF0oT1zG9+Bwn713vYyreFl3S4TmM2KZSbW7Qt7wdre4HDbOkIl+yvLjEp5KajHAn6wtU+d6/Dzks1B3IuwR9PQELaEbRicArI8i2Eo64nFqTrDqCEqL86U7IvPVTYfVUathz58sLOt5A99aHcsAIM1D7S78kVArOs8XhzQk0IHv11xIpFDPtb3tqO+lOXpsZoUOvuVd1+3nYExA+m9GhLnkRfnk4u/pNgcs1bqrlfMlrz3AV9MUnNwS1uLdN9dmduavN7M/utK0l6VdJ2wqEamXwz1f+Q6dhIIWiwWZCO1c8TxH4NFebSPzVpG5y6ghGOoHqYtZjNl3sqHa1ksfe3oM4zSLiS4fPc/hGeHc+9bpfq1sNNSw9kVDqajhvWKuIdrjLDiNxjBVYCXdZaXk06xgUvaQNk/KvqqT3mQqpKUMZC3mfd6cx+pZei4TsiGg8G7n+o9t1iy8e6F13GtrrKDNQ0A2NPqBmedwJvUZGwdPnCqZz1FNeSj7erFJOQvh5wU1N1LrIsHR/QGqJmT1PFKE8j8OFV7uJdfENrLS+hBlYFK0sX/ouZJgpu/+iaCGSsmuO4eETNxHNqY2cWIsbwqOyjVjKRvAJ0cojWnQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
