travis:
  secure:
    BINSTAR_TOKEN: 1e0He2EZrOvWZUDFi0UBIC9cvbcqS95nr8Yz5Spz3Ys6QUzj8jX564PSQSsMvkfrDuyPI29XSab7dcvNQgEqogd2VBGgt1cyGbbF6NIT3I6n6jjI1blgOix2pzFMjUkKxsLzlpOvLf6wCTwy2MlGxAVtjahLaqatSJZg47+Q+vCkO37iGT5AZKVuPur+9WikFy1NESeG4iyU6WPRmIbdAJahgryroG6XSG7P57l8YX7Kx4sMP3difHERciOTGJJl3uYcywZlbWyWH6uhTKtruHPnZt6MUq9j5hlcZ1WNabtEP0Xf6o757J/TFOSiKf/v3guunFin3+xKBb0ebLfCtlojPXJ1/XWWdHOdL9aigk54Qvhhayv8g2PKPQpS5h4aGQ6W3H5BrI8H4UoeWKgRpi+RDN/yA/NkE1lZ+JRvcy9UUbEHnbPZpvMmQxJHkKOs8aRZjPU2GsvRimOeEDN8Sdfuav8lfGCNGSXECHzog/HkwpNTwls0NqthQXZ09ePYWY7qvPoTgQdvdNHRy9ZyljuMqc2dN3RhG9+H/2xw1jwweRHYQbllegVBwZTTBEoy/82g4yHW8WyaAXw7jOYQ1G5aSTRmsvaDOw1mElonfJpmaYg4NUyXgq5vXjAdSU+VhT3o60BTJyQZaF3dyuvgkTb2z3+2KNocMs34CuISZhc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
